name: Build Electron App (Windows & macOS)

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows App
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create .env for backend
        run: |
          echo "COVAMO_USERNAME=${{ secrets.COVAMO_USERNAME }}" >> backend/.env
          echo "COVAMO_PASSWORD=${{ secrets.COVAMO_PASSWORD }}" >> backend/.env

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pyinstaller

      - name: Build Python backend exe
        run: |
          python -m PyInstaller --onefile backend/app.py --distpath backend/dist --workpath backend/build --specpath backend

      - name: Move backend exe to resources
        run: |
          mkdir -p resources/backend
          mv backend/dist/app.exe resources/backend/

      - name: Build Vite frontend
        run: npm run build
        env:
          ENV_SECRET_KEY: ${{ secrets.ENV_SECRET_KEY }}

      - name: Build Electron Windows App
        run: npx electron-builder --win --x64
        env:
          ENV_SECRET_KEY: ${{ secrets.ENV_SECRET_KEY }}

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe

  # build-macos:
  #   runs-on: macos-latest
  #   name: Build macOS App
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20

  #     - name: Install Node dependencies
  #       run: npm install

  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.11

  #     - name: Create .env for backend
  #       run: |
  #         echo "COVAMO_USERNAME=${{ secrets.COVAMO_USERNAME }}" >> backend/.env
  #         echo "COVAMO_PASSWORD=${{ secrets.COVAMO_PASSWORD }}" >> backend/.env

  #     - name: Install Python dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r backend/requirements.txt
  #         pip install pyinstaller

  #     - name: Build Python backend binary
  #       run: |
  #         python -m PyInstaller --onefile backend/app.py --distpath backend/dist --workpath backend/build --specpath backend
  #         mkdir -p resources/backend
  #         mv backend/dist/app resources/backend/

  #     - name: Build Vite frontend
  #       run: npm run build
  #       env:
  #         ENV_SECRET_KEY: ${{ secrets.ENV_SECRET_KEY }}

  #     - name: Build Electron macOS App
  #       run: npm run electron:build:mac
  #       env:
  #         ENV_SECRET_KEY: ${{ secrets.ENV_SECRET_KEY }}

  #     - name: Upload macOS installer
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: macos-installer
  #         path: dist/*.dmg
